<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category            design
 * @package             default_defaut
 * @author              Firedrago Magento
 * @license             http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version             $Id: selectpayment.phtml 5 2013-10-10 13:08:44Z sapolhei $
 */
?>
<p><b>
<?php
  echo "<img onerror='if(typeof selectedPayment === \"undefined\") selectedPayment=\"../../../web/img/logos/payment-mpay24\"; this.src=\"https://www.mpay24.com/merchadm/img/ptypes/\" + selectedPayment + \".png\";this.title=brand;this.alt=brand;' style='max-width: 40%;padding-top: 5px;' src='https://www.mpay24.com/merchadm/img/ptypes/".$this->getPMethId().".png' alt='".$this->getPType()."-".$this->getBrand()."' title='".$this->getPType()."-".$this->getBrand()."'>".' ('.Mage::getStoreConfig('payment/mpay24/title').')' ?></b><br/>

<?php if($this->getMethod()->getData('info_instance')->getOrder() !== null): ?>
  <?php echo Mage::helper('mpay24')->__("Approval code") . ": " . $this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('appr_code')) ?><br/>
<?php endif; ?>