<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category            design
 * @package             default_defaut
 * @author              Anna Sadriu (mPAY24 GmbH)
 * @license             http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version             $Id: selectpayment.phtml 6252 2015-03-26 15:57:57Z anna $
 */
?>
<?php echo $this->getMethod()->getTitle() . " - " . $this->getPType() . " - " . $this->getBrand(); ?>
    {{pdf_row_separator}}
<?php echo 'mPAYTID: ' . $this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('mpay_tid')) ?>
    {{pdf_row_separator}}
<?php echo Mage::helper('mpay24')->__("Approval code") . ": " .$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('appr_code')); ?>
    {{pdf_row_separator}}

<?php if($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_holder')): ?>
<?php echo Mage::helper('mpay24')->__("Account holder") . ": " .$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_holder')); ?>
    {{pdf_row_separator}}
<?php endif; ?>
<?php if($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_number')): ?>
<?php echo Mage::helper('mpay24')->__("Account number") . ": " .$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_number')); ?>
    {{pdf_row_separator}}
<?php endif; ?>
<?php if($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('bank_code')): ?>
<?php echo Mage::helper('mpay24')->__("Bank code") . ": " .$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('bank_code')); ?>
    {{pdf_row_separator}}
<?php endif; ?>
<?php if($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('bank_name')): ?>
<?php echo Mage::helper('mpay24')->__("Bank name") . ": " .$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('bank_name')); ?>
    {{pdf_row_separator}}
<?php endif; ?>
<?php if($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('reference')): ?>
<?php echo Mage::helper('mpay24')->__("Reference") . ": " .$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('reference')); ?>
    {{pdf_row_separator}}
<?php endif; ?>