<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category            design
 * @package             default_defaut
 * @author              Firedrago Magento
 * @license             http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version             $Id: selectpayment.phtml 29 2014-11-10 13:21:51Z sapolhei $
 */
?>
<p><b>
<?php echo "<label for='brand'>".Mage::helper('mpay24')->__("Payment method")."</label><span name='brand' style='float: right; margin-right: 400px;'><img onerror='if(typeof selectedPayment === \"undefined\") selectedPayment=\"../../../img/logos/payment-mpay24\"; this.src=\"https://www.mpay24.com/web/img/logos/ptypes/\" + selectedPayment + \".png\";this.title=brand;this.alt=brand;' style='max-width: 40%;padding-top: 5px;' src='https://www.mpay24.com/web/img/logos/ptypes/".$this->getPMethId().".png' alt='".$this->getPType()."-".$this->getBrand()."' title='".$this->getPType()."-".$this->getBrand()."'>".' ('.Mage::getStoreConfig('payment/mpay24/title').')'."</span>"; ?></b><br/>
  <br/>
<?php if($this->getMethod()->getData('info_instance')->getOrder() !== null): ?>
  <b><?php echo "<label for='mpaytid'>MPAYTID</label><span name='mpaytid' style='float: right; margin-right: 400px;'>".$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('mpay_tid'))."</span>"; ?></b>
  <br/><b><?php echo "<label for='appr_code'>".Mage::helper('mpay24')->__("Approval code")."</label><span name='appr_code' style='float: right; margin-right: 400px;'>".$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('appr_code'))."</span>"; ?></b>

<?php if($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_holder')): ?>
  <br/><b><?php echo "<label for='acct_holder'>".Mage::helper('mpay24')->__("Account holder")."</label><span name='acct_holder' style='float: right; margin-right: 400px;'>".$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_holder'))."</span>"; ?></b>
<?php endif; ?>
<?php if($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_holder')): ?>
  <br/><b><?php echo "<label for='acct_number'>".Mage::helper('mpay24')->__("Account number")."</label><span name='acct_number' style='float: right; margin-right: 400px;'>".$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_number'))."</span>"; ?></b>
<?php endif; ?>
<?php if($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_holder')): ?>
  <br/><b><?php echo "<label for='bank_code'>".Mage::helper('mpay24')->__("Bank code")."</label><span name='bank_code' style='float: right; margin-right: 400px;'>".$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('bank_code'))."</span>"; ?></b>
<?php endif; ?>
<?php if($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_holder')): ?>
  <br/><b><?php echo "<label for='bank_name'>".Mage::helper('mpay24')->__("Bank name")."</label><span name='bank_name' style='float: right; margin-right: 400px;'>".$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('bank_name'))."</span>"; ?></b>
<?php endif; ?>
<?php if($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('acct_holder')): ?>
  <br/><b><?php echo "<label for='reference'>".Mage::helper('mpay24')->__("Reference")."</label><span name='reference' style='float: right; margin-right: 400px;'>".$this->htmlEscape($this->getInfo()->getOrder()->getPayment()->getAdditionalInformation('reference'))."</span>"; ?></b>
<?php endif; ?>
<?php endif; ?>
</p><br/>