<?php
/**
 * @category            design
 * @package             base_defaut
 * @author              Anna Sadriu (mPAY24 GmbH)
 * @license             http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version             $Id: area.phtml 6253 2015-03-26 16:05:00Z anna $
 */
?>
<?php
$_code=$this->getMethodCode();

if(Mage::getStoreConfig('mpay24/mpay24/payments_active') == 'true') {
  $brandsAndTypes = explode(", ", Mage::getStoreConfig('mpay24/mpay24/active_payment_types'));
  $brands = array();
  foreach($brandsAndTypes as $brandAndType)
    $brands[substr($brandAndType, 0, strpos($brandAndType, "=>"))] = substr($brandAndType, strpos($brandAndType, "=>")+2);
}
?>
<script type="text/javascript">
  var selectedPayment = "../../../img/logos/payment-mpay24.svg";
  var brand = "";
</script>

<?php if(Mage::getStoreConfig('mpay24/mpay24/payments_active') == 'true' && Mage::getStoreConfig('mpay24/mpay24/forced_preselection') == 1): ?>
<script type="text/javascript">
  setOnClick('<?= Mage::helper('mpay24')->__("Please choose a payment system..."); ?>');
</script>
<?php endif;?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none;">
  <li>
    <b>
      <?php if(Mage::getStoreConfig('mpay24/mpay24/payments_active') == 'true')
              if(Mage::getStoreConfig('mpay24/mpay24/forced_preselection') == 1)
                echo Mage::helper('mpay24')->__("Please click an icon to choose a payment system...");
              else
                echo Mage::helper('mpay24')->__("You can choose the payment system you want to use now or do it when you are redirected to the mPAY24 pay page after placing the order.");
            else
              echo Mage::helper('mpay24')->__("You can choose the payment system you want to use after you are redirected to the mPAY24 pay page after placing the order.");
      ?>
    </b>
  </li>

  <?php if(Mage::getStoreConfig('mpay24/mpay24/payments_active') == 'true'):?>
    <li>
      <table style="padding:10px 15px 15px; min-width: 320px;">
        <tr>
          <td height="1" colspan="3"></td>
          <td height="1" bgcolor="#b3b3b3"></td>
          <td height="1" colspan="3"></td>
        </tr>
        <tr>
          <td height="1" colspan="2"></td>
          <td height="1" width="2" bgcolor="#b3b3b3"></td>
          <td height="1" bgcolor="#ffffff"></td>
          <td height="1" width="2" bgcolor="#b3b3b3"></td>
          <td height="1" colspan="2"></td>
        </tr>
        <tr>
          <td height="2" width="1"></td>
          <td height="2" width="1" bgcolor="#b3b3b3"></td>
          <td height="2" colspan="3" bgcolor="#ffffff"></td>
          <td height="2" width="1" bgcolor="#b3b3b3"></td>
          <td height="2" width="1"></td>
        </tr>
        <tr>
          <td width="1" bgcolor="#b3b3b3"></td>
          <td width="3" colspan="2" bgcolor="#ffffff"></td>
          <td bgcolor="#ffffff">
            <table id='mpay24_table' style="width: 100%;">
              <colgroup>
                <col width="70%">
                <col width="30%">
              </colgroup>
              <tr>
                <td colspan="2">
                  <div>
                    <?php 
                          $j = 1;
                          foreach ($this->getActiveMethods() as $id => $payment):
                            if($payment['ACTIVE'] == 1) {
                              if(strlen($id) == 1)
                                $id = "00$id";
                              elseif(strlen($id) == 2)
                                $id = "0$id";
                              
                              $addInfo = "";
                              
                              if(Mage::getStoreConfig("mpay24/mpay24/forced_preselection") == 1 && Mage::getStoreConfig("mpay24/mpay24/tax_$j") <> 0) {
                                $addInfo .= " - ";
                                
                                $lab = "";
                                if(Mage::getStoreConfig("mpay24/mpay24/tax_$j") > 0)
                                  $lab = Mage::helper('mpay24')->__("Payment charge");
                                else
                                  $lab = Mage::helper('mpay24')->__("Payment discount");
                                
                                if(Mage::getStoreConfig("mpay24/mpay24/tax_type_$j") == 'absolute')
                                  $addInfo .= Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
                                $addInfo .= " " . abs(Mage::getStoreConfig("mpay24/mpay24/tax_$j"));
                            
                                if(Mage::getStoreConfig("mpay24/mpay24/tax_type_$j") == 'percent')
                                  $addInfo .= "%";
                            
                                $addInfo .= " " . $lab;
                              }
                              
                      ?>
                        <div style="border:5px solid transparent; float:left;">
                          <div style="border: 1px inset transparent;">
                            <a href="#" onclick="
                            brand = '<?php echo $payment['DESCR']?>';
                            if(this.parentNode.getAttribute('style') == 'border: 1px inset transparent;' || this.parentNode.getAttribute('style') == 'border: 1px inset transparent; border-image: none;') {
                              var inputs = document.getElementById('mpay24_table').getElementsByTagName('input');
                        
                              for(var i=0; i<inputs.length; i++) {
                                inputs[i].parentNode.setAttribute('style', 'border: 1px inset transparent;');
                                inputs[i].disabled = true;
                              }
                        
                              document.getElementById('mpay24_table').disabled = true;
                        
                              this.parentNode.setAttribute('style', 'border: 1px inset blue;');
                              document.getElementById('<?php echo $id;?>').disabled = false;
                        
                              selectedPayment = '<?php echo "$id.png";?>';
                              payment.save();
                            } else {
                              this.parentNode.setAttribute('style', 'border: 1px inset transparent;');
                              document.getElementById('<?php echo $id;?>').disabled = true;
                              document.getElementById('mpay24_table').disabled = false;
                            }
                            "><img src='https://www.mpay24.com/web/img/logos/ptypes/<?php echo $id?>.png' alt='<?php echo $payment['DESCR'] . $addInfo?>' title='<?php echo $payment['DESCR'] . $addInfo?>' ></a>
                            <input type="hidden" id='<?php echo $id;?>' name='mpay24_ps' value='<?php echo "mpay24_".$id . "_" . $j;?>' disabled />
                          </div>
                        </div>
                      <?php 
                    } $j++;
                    endforeach; ?>
                    <input type="hidden" id='mpay24_all' name='mpay24_ps' value='false' />
                  </div>
                </td>
              </tr>
              <tr>
                <td colspan="2">
                  <div style="padding-bottom: 2px; border-top: 1px solid #b3b3b3"></div>
                </td>
              </tr>
              <tr>
                <td></td>
                <td>
                  <img style="float:right" src="https://www.mpay24.com/web/img/logos/payment-mpay24.svg" alt="mPAY24" title="mPAY24" width="40%" >
                </td>
              </tr>
            </table>
          </td>
          <td width="3" colspan="2" bgcolor="#ffffff"></td>
          <td width="1" bgcolor="#b3b3b3"></td>
        </tr>
        <tr>
          <td height="2" width="1"></td>
          <td height="2" width="1" bgcolor="#b3b3b3"></td>
          <td height="2" colspan="3" bgcolor="#ffffff"></td>
          <td height="2" width="1" bgcolor="#b3b3b3"></td>
          <td height="2" width="1"></td>
        </tr>
        <tr>
          <td height="1" colspan="2"></td>
          <td height="1" width="2" bgcolor="#b3b3b3"></td>
          <td height="1" bgcolor="#ffffff"></td>
          <td height="1" width="2" bgcolor="#b3b3b3"></td>
          <td height="1" colspan="2"></td>
        </tr>
        <tr>
          <td height="1" colspan="3"></td>
          <td height="1" bgcolor="#b3b3b3"></td>
          <td height="1" colspan="3"></td>
        </tr>
      </table>
    </li>
  <?php endif;?>
</ul>