<?php
/**
 * @category            design
 * @package             base_defaut
 * @author              Anna Sadriu (mPAY24 GmbH)
 * @license             http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version             $Id: logos.phtml 6253 2015-03-26 16:05:00Z anna $
 */
?>
<?php if($this->getPaymentLogoSrc1() != ""):?>
<img src="<?= $this->escapeHtml($this->getPaymentLogoSrc1())?>" alt="<?= $this->getAlt1() ?>" class="v-middle brand_logo"/>
<?php endif;?>

<?php if($this->getPaymentLogoSrc2() != ""):?>
<img src="<?= $this->escapeHtml($this->getPaymentLogoSrc2())?>" alt="<?= $this->getAlt2() ?>" class="v-middle brand_logo"/>
<?php endif;?>

<?php if($this->getPaymentLogoSrc3() != ""):?>
<img src="<?= $this->escapeHtml($this->getPaymentLogoSrc3())?>" alt="<?= $this->getAlt3() ?>" class="v-middle brand_logo"/>
<?php endif;?>

<?php if($this->getPaymentLogoSrc4() != ""):?>
<img src="<?= $this->escapeHtml($this->getPaymentLogoSrc4())?>" alt="<?= $this->getAlt4() ?>" class="v-middle brand_logo"/>
<?php endif;?>

<?php if($this->getPaymentLogoSrc5() != ""):?>
<img src="<?= $this->escapeHtml($this->getPaymentLogoSrc5())?>" alt="<?= $this->getAlt5() ?>" class="v-middle brand_logo" />
<?php endif;?>