<?php
/**
 * @category            design
 * @package             base_defaut
 * @author              Anna Sadriu (mPAY24 GmbH)
 * @license             http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version             $Id: paypal.phtml 6253 2015-03-26 16:05:00Z anna $
 */
?>
<?php
$_code = $this->getMethodCode();
?>
<ul id="payment_form_<?= $_code ?>" style="display:none;" class="form-list">
  <li>
    <?=  $this->getRedirectMessage()?>
  </li>
</ul>